// Regenerate the offline price archive from models.dev.
//
// Run `pnpm sync`, review the diff, commit. Nothing in this package's price
// data is meant to be typed by hand — the only hand-maintained pricing
// facts left are the ones no upstream publishes at all (peak/off-peak
// schedules and fast-tier multipliers).
//
// This builds an ARCHIVE, not a table. models.dev — like OpenRouter,
// LiteLLM and ccusage — publishes one number per model: whatever it costs
// today. Applied naively that re-prices history, so a vendor raising a rate
// silently inflates last month's bill. Each sync therefore *appends* a
// period dated today rather than overwriting, and the resulting schedule
// keeps old months on old rates.
//
// Two consequences worth knowing:
//
//   - An effective date is only as precise as the sync cadence. A price
//     that changed three weeks before a sync is dated at the sync. Sync
//     often if that matters.
//   - The merge is APPEND-ONLY in both directions: a model that disappears
//     upstream keeps its whole history. Stored model strings are immortal,
//     and a row that silently prices at $0 is worse than a stale rate.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { mergeSnapshot, SYNC_PROVIDERS } from '../src/catalog/sync'

const SOURCE = 'https://models.dev/api.json'
const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'catalog', 'snapshot.json')

const today = new Date().toISOString().slice(0, 10)

const response = await fetch(SOURCE, { headers: { accept: 'application/json' } })
if (!response.ok) {
  console.error(`[sync] ${SOURCE} -> HTTP ${response.status}`)
  process.exit(1)
}
const api = await response.json()
const previous = JSON.parse(readFileSync(OUT, 'utf8'))

// The merge itself lives in src/catalog/sync.ts so it can be tested without
// a network call — it carries the append-only guarantee, and this script is
// only the IO around it.
const { models, added, repriced, retained } = mergeSnapshot(previous.models, api, SYNC_PROVIDERS, today)

const keys = Object.keys(models).sort()

// Hand-rolled so each model stays on one line: this file is reviewed as a
// diff, and a reprice should read as a one-line change.
const header = {
  $comment: 'GENERATED by scripts/sync-snapshot.ts — do not edit by hand. Each entry is [displayName, periods]; each period is [effectiveFrom|null, input, cacheWrite, cacheRead, output] in USD per million tokens. Append-only: periods accumulate so history is never re-priced, and entries upstream has dropped are retained.',
  source: SOURCE,
  syncedAt: today,
}
const body = keys.map(k => `    ${JSON.stringify(k)}: ${JSON.stringify(models[k])}`).join(',\n')
writeFileSync(OUT, `{\n${
  Object.entries(header).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n')
},\n  "models": {\n${body}\n  }\n}\n`)

const scheduled = keys.filter(k => models[k][1].length > 1).length
console.log(`[sync] ${keys.length} models — ${added} added, ${repriced} repriced, ${scheduled} now carry a price history, ${retained.length} retained after upstream removal`)
