// Regenerate the offline price archive from models.dev.
//
// Run `pnpm sync`, review the diff, commit. Nothing in this package's price
// data is meant to be typed by hand — the only hand-maintained pricing
// facts left are the ones no upstream publishes at all (peak/off-peak
// schedules and fast-tier multipliers).
//
// This script is only the IO. The merge — and the reasoning for why it
// appends rather than overwrites — lives in `mergeSnapshot`, where it can be
// tested without a network call.
//
// The one consequence to keep in mind while running it: an effective date is
// only as precise as the sync cadence. A price that changed three weeks
// before a sync is dated at the sync. Sync often if that matters.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
// The archive is filtered to exactly the providers the live index ranks as
// first-party. If the two lists disagree, a vendor-vs-reseller price gap
// reads as a change over time and gets grafted into the history as one.
import { DEFAULT_PROVIDER_PRIORITY } from '../src/catalog/modelsdev'
import { mergeSnapshot } from '../src/catalog/sync'

const SOURCE = 'https://models.dev/api.json'
const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'catalog', 'snapshot.json')

const today = new Date().toISOString().slice(0, 10)

const response = await fetch(SOURCE, { headers: { accept: 'application/json' } })
if (!response.ok) {
  console.error(`[sync] ${SOURCE} -> HTTP ${response.status}`)
  process.exit(1)
}
const api = await response.json()
const previous = JSON.parse(readFileSync(OUT, 'utf8'))

const { models, added, repriced, backfilled, retained } = mergeSnapshot(previous.models, api, DEFAULT_PROVIDER_PRIORITY, today)

const keys = Object.keys(models).sort()

// Hand-rolled so each model stays on one line: this file is reviewed as a
// diff, and a reprice should read as a one-line change.
const header = {
  $comment: 'GENERATED by scripts/sync-snapshot.ts — do not edit by hand. Each entry is [displayName, periods]; each period is [effectiveFrom|null, input, cacheWrite, cacheRead, output] in USD per million tokens, optionally followed by long-context tiers as [abovePromptTokens, input, cacheWrite, cacheRead, output]. Append-only: periods accumulate so history is never re-priced, and entries upstream has dropped are retained.',
  source: SOURCE,
  syncedAt: today,
}
const body = keys.map(k => `    ${JSON.stringify(k)}: ${JSON.stringify(models[k])}`).join(',\n')
writeFileSync(OUT, `{\n${
  Object.entries(header).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n')
},\n  "models": {\n${body}\n  }\n}\n`)

const scheduled = keys.filter(k => models[k][1].length > 1).length
const tiered = keys.filter(k => models[k][1].some(p => p[5] !== undefined)).length
console.log(`[sync] ${keys.length} models — ${added} added, ${repriced} repriced, ${backfilled} gained long-context tiers in place, ${scheduled} carry a price history, ${tiered} carry a long-context tier, ${retained.length} retained after upstream removal`)
